-- raez_migration_v4_image_backfill.sql
-- Idempotent backfill of Cloudinary imageUrl/imagePublicId for products that
-- still have NULL/empty values. Captured from the dev DB after admin uploads.
-- Safe to re-run; never overwrites a non-empty imageUrl.

BEGIN TRANSACTION;

UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579209/raez/products/bfzx0nihsurnp5f7nvvt.png', imagePublicId = 'raez/products/bfzx0nihsurnp5f7nvvt' WHERE sku = 'HTR-001' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579216/raez/products/oyej4zxnlckxxppfrnuq.png', imagePublicId = 'raez/products/oyej4zxnlckxxppfrnuq' WHERE sku = 'HTR-002' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579224/raez/products/pgrefaplg6upfn1aybum.png', imagePublicId = 'raez/products/pgrefaplg6upfn1aybum' WHERE sku = 'HTR-003' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579226/raez/products/codyx0nljfe0w70iiwh6.png', imagePublicId = 'raez/products/codyx0nljfe0w70iiwh6' WHERE sku = 'HTR-004' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579228/raez/products/ircjoedepedlh30slnsr.png', imagePublicId = 'raez/products/ircjoedepedlh30slnsr' WHERE sku = 'HTR-005' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579229/raez/products/mkew0nyfustl544aiyvy.png', imagePublicId = 'raez/products/mkew0nyfustl544aiyvy' WHERE sku = 'HTR-006' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579232/raez/products/qurokysvfgpvetlhq0lk.png', imagePublicId = 'raez/products/qurokysvfgpvetlhq0lk' WHERE sku = 'HTR-007' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579234/raez/products/vwwyf7eyddxeknx2fkve.png', imagePublicId = 'raez/products/vwwyf7eyddxeknx2fkve' WHERE sku = 'HTR-008' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579241/raez/products/l35qdn9s7otwfk6a7dmh.png', imagePublicId = 'raez/products/l35qdn9s7otwfk6a7dmh' WHERE sku = 'HTR-009' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579247/raez/products/k6z6a3xq1kndrh0p2trj.png', imagePublicId = 'raez/products/k6z6a3xq1kndrh0p2trj' WHERE sku = 'HTR-010' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579250/raez/products/vkyytogyowq6g6na07gr.png', imagePublicId = 'raez/products/vkyytogyowq6g6na07gr' WHERE sku = 'HTR-011' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579252/raez/products/bjnqh9ibsafyltzjwejg.png', imagePublicId = 'raez/products/bjnqh9ibsafyltzjwejg' WHERE sku = 'HTR-012' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579254/raez/products/hoixv5jmpngtvru1ss1g.png', imagePublicId = 'raez/products/hoixv5jmpngtvru1ss1g' WHERE sku = 'HTR-013' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579257/raez/products/hbwp07gciwzs9yvhkiyx.png', imagePublicId = 'raez/products/hbwp07gciwzs9yvhkiyx' WHERE sku = 'HTR-014' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579259/raez/products/b1wrxhpsy3ffobmvgzv0.png', imagePublicId = 'raez/products/b1wrxhpsy3ffobmvgzv0' WHERE sku = 'HTR-015' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579261/raez/products/p9aabunesgwqr6u8nm7z.png', imagePublicId = 'raez/products/p9aabunesgwqr6u8nm7z' WHERE sku = 'HTR-016' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579263/raez/products/i8outxyloacf8v1ncxtj.png', imagePublicId = 'raez/products/i8outxyloacf8v1ncxtj' WHERE sku = 'HTR-017' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579264/raez/products/rge3hliirgqaeiyzjavq.png', imagePublicId = 'raez/products/rge3hliirgqaeiyzjavq' WHERE sku = 'HTR-018' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579267/raez/products/wz2d54dhjdafretkrmba.png', imagePublicId = 'raez/products/wz2d54dhjdafretkrmba' WHERE sku = 'HTR-019' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579268/raez/products/g7gdjxsi7wglblnqxnx4.png', imagePublicId = 'raez/products/g7gdjxsi7wglblnqxnx4' WHERE sku = 'HTR-020' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579270/raez/products/thuj9zzaubqlx3pygrbq.png', imagePublicId = 'raez/products/thuj9zzaubqlx3pygrbq' WHERE sku = 'HTR-021' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579273/raez/products/iymy94qhqznj4z4va4ee.png', imagePublicId = 'raez/products/iymy94qhqznj4z4va4ee' WHERE sku = 'HTR-022' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579275/raez/products/yddwcspicb1qbr4oqnbr.png', imagePublicId = 'raez/products/yddwcspicb1qbr4oqnbr' WHERE sku = 'HTR-023' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579276/raez/products/s0tsjt2yuzhvgqydbjx2.jpg', imagePublicId = 'raez/products/s0tsjt2yuzhvgqydbjx2' WHERE sku = 'HTR-024' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579281/raez/products/hbs3lsnvodilludmkc4y.png', imagePublicId = 'raez/products/hbs3lsnvodilludmkc4y' WHERE sku = 'HTR-025' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579283/raez/products/ngi8ph6caemkmmke26j9.png', imagePublicId = 'raez/products/ngi8ph6caemkmmke26j9' WHERE sku = 'HTR-026' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579288/raez/products/sjpxc7t9kvxeqhjyyvu9.png', imagePublicId = 'raez/products/sjpxc7t9kvxeqhjyyvu9' WHERE sku = 'HTR-027' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579289/raez/products/nrpyanqljpixxtxakhap.png', imagePublicId = 'raez/products/nrpyanqljpixxtxakhap' WHERE sku = 'HTR-028' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579291/raez/products/pkzhwoy2du9bnrimqnjf.png', imagePublicId = 'raez/products/pkzhwoy2du9bnrimqnjf' WHERE sku = 'HTR-029' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579293/raez/products/xjn2bxh8dlu104wyuefo.png', imagePublicId = 'raez/products/xjn2bxh8dlu104wyuefo' WHERE sku = 'HTR-030' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579295/raez/products/rgvufzp4s2ztrjkkopdh.png', imagePublicId = 'raez/products/rgvufzp4s2ztrjkkopdh' WHERE sku = 'HTR-031' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579297/raez/products/dpnxzpwamrzxrfzd1chh.png', imagePublicId = 'raez/products/dpnxzpwamrzxrfzd1chh' WHERE sku = 'HTR-032' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579302/raez/products/wznfremcglihyvs0pl0j.png', imagePublicId = 'raez/products/wznfremcglihyvs0pl0j' WHERE sku = 'HTR-033' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579310/raez/products/jkglhp8mlceiqkwouxvm.png', imagePublicId = 'raez/products/jkglhp8mlceiqkwouxvm' WHERE sku = 'HTR-034' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579312/raez/products/ndbpkwipvai5a1q6t2wh.png', imagePublicId = 'raez/products/ndbpkwipvai5a1q6t2wh' WHERE sku = 'HTR-035' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579314/raez/products/p2qcnwthstt9dvpuifqe.png', imagePublicId = 'raez/products/p2qcnwthstt9dvpuifqe' WHERE sku = 'HTR-036' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579316/raez/products/cu4nf6hktjfmmslbh5rs.png', imagePublicId = 'raez/products/cu4nf6hktjfmmslbh5rs' WHERE sku = 'HTR-037' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579318/raez/products/hfzc7wn7yml3yxfy67ji.png', imagePublicId = 'raez/products/hfzc7wn7yml3yxfy67ji' WHERE sku = 'HTR-038' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579320/raez/products/buj6xa23aeyud0qnysk8.png', imagePublicId = 'raez/products/buj6xa23aeyud0qnysk8' WHERE sku = 'HTR-039' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579326/raez/products/si2qzgjsikm9sck1pwuy.png', imagePublicId = 'raez/products/si2qzgjsikm9sck1pwuy' WHERE sku = 'HTR-040' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579328/raez/products/qfey5s6b3cmngxqbul9h.png', imagePublicId = 'raez/products/qfey5s6b3cmngxqbul9h' WHERE sku = 'HTR-041' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579336/raez/products/y3f8tnymtal4p7ubnalt.png', imagePublicId = 'raez/products/y3f8tnymtal4p7ubnalt' WHERE sku = 'HTR-042' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579338/raez/products/kpmystoniyyxgy2389vm.png', imagePublicId = 'raez/products/kpmystoniyyxgy2389vm' WHERE sku = 'HTR-043' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579341/raez/products/hyrlx9zbgtv21rk2wnov.png', imagePublicId = 'raez/products/hyrlx9zbgtv21rk2wnov' WHERE sku = 'HTR-044' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579345/raez/products/pp5a9pji7mbkdupqqoa3.png', imagePublicId = 'raez/products/pp5a9pji7mbkdupqqoa3' WHERE sku = 'HTR-045' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579348/raez/products/jecpplt7vut1xt4a1tf3.png', imagePublicId = 'raez/products/jecpplt7vut1xt4a1tf3' WHERE sku = 'HTR-046' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579350/raez/products/cwf6b6mpdaqhxcbzralh.png', imagePublicId = 'raez/products/cwf6b6mpdaqhxcbzralh' WHERE sku = 'HTR-047' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579353/raez/products/ue46eslcpz6bqgl99skq.png', imagePublicId = 'raez/products/ue46eslcpz6bqgl99skq' WHERE sku = 'HTR-048' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579355/raez/products/ryagfyfrpcptarvb8ybk.png', imagePublicId = 'raez/products/ryagfyfrpcptarvb8ybk' WHERE sku = 'HTR-049' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579357/raez/products/vvua2dzy8yw7jqp601xz.png', imagePublicId = 'raez/products/vvua2dzy8yw7jqp601xz' WHERE sku = 'HTR-050' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579366/raez/products/tj9kzgjn8njujnamt0sj.png', imagePublicId = 'raez/products/tj9kzgjn8njujnamt0sj' WHERE sku = 'HTR-051' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579373/raez/products/p43k9jhlylysmrnchg4r.png', imagePublicId = 'raez/products/p43k9jhlylysmrnchg4r' WHERE sku = 'HTR-052' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579375/raez/products/oflig8vwjpaffuuchbzj.png', imagePublicId = 'raez/products/oflig8vwjpaffuuchbzj' WHERE sku = 'HTR-053' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579377/raez/products/t7bqwjiccx54o4itusp5.png', imagePublicId = 'raez/products/t7bqwjiccx54o4itusp5' WHERE sku = 'HTR-054' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579378/raez/products/yllgmobirie9m3amzukk.png', imagePublicId = 'raez/products/yllgmobirie9m3amzukk' WHERE sku = 'HTR-055' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579387/raez/products/jhtpq3ce50drmi4zji22.png', imagePublicId = 'raez/products/jhtpq3ce50drmi4zji22' WHERE sku = 'HTR-056' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579203/raez/products/wcxiprfcwkcansl8sv92.png', imagePublicId = 'raez/products/wcxiprfcwkcansl8sv92' WHERE sku = 'SKU-FIN-001' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777578482/raez/products/ctc8efjztgfkwpyo3inz.jpg', imagePublicId = 'raez/products/ctc8efjztgfkwpyo3inz' WHERE sku = 'TC-10' AND (imageUrl IS NULL OR imageUrl = '');
UPDATE products SET imageUrl = 'https://res.cloudinary.com/dzfltqfbk/image/upload/v1777579203/raez/products/wcxiprfcwkcansl8sv92.png', imagePublicId = 'raez/products/wcxiprfcwkcansl8sv92' WHERE sku = 'TC-11' AND (imageUrl IS NULL OR imageUrl = '');

COMMIT;
